<?php
/**
 * Dependency manifest for the breadcrumbs editor script.
 *
 * Normally generated by @wordpress/scripts. Written by hand here because the
 * theme deliberately has no build step — the script uses only globals that
 * WordPress already enqueues.
 */

return [
	'dependencies' => [
		'wp-blocks',
		'wp-block-editor',
		'wp-element',
		'wp-server-side-render',
	],
	'version'      => '1.0.0',
];
